# Symfony service configuration for SQS integration
services:
    # SQS Message Sender
    app.sqs_message_sender:
        class: AppBundle\Helper\RJIndex\SqsMessageSender
        arguments:
            $awsRegion: '%env(AWS_REGION)%'
            $queueUrl: '%env(SQS_QUEUE_URL)%'
            $accessKey: '%env(AWS_ACCESS_KEY_ID)%'
            $secretKey: '%env(AWS_SECRET_ACCESS_KEY)%'
    
    # Updated Import Queue Creator
    app.import_queue_creator:
        class: AppBundle\Helper\RJIndex\ImportQueueCreatorUpdated
        arguments:
            $sqsMessageSender: '@app.sqs_message_sender'
    
    # Original Import Queue Creator (for fallback)
    app.import_queue_creator_original:
        class: AppBundle\Helper\RJIndex\ImportQueueCreator
        arguments:
            $importQueueHelper: '@app.import_queue_helper'
            $teckizJournalManager: '@app.teckiz_journal_manager'
            $teckizArticleHelper: '@app.teckiz_article_helper'
            $companyModuleMapperRepository: '@app.company_module_mapper_repository'
            $hostUrlCreator: '@app.host_url_creator'
            $ojsOaiXmlImport: '@app.ojs_oai_xml_import'
